services:
  api:
    environment:
      - PORT=8881
    image: getaround-api-jedha
    build: ./api
    volumes:
      - ./api/src:/app/src
    ports:
      - "8881:8881"
    networks:
      - getaroundnetwork
  dashboard:
    environment:
      - PORT=8882
    image: getaround-dashboard-jedha
    build: ./dashboard
    volumes:
      - ./dashboard/src:/app/src
    ports:
      - "8882:8882"
    networks:
      - getaroundnetwork
  mlflow:
    environment:
      - PORT=8883
    image: getaround-mlflow-jedha
    build: ./mlflow
    ports:
      - "8883:8883"
    networks:
      - getaroundnetwork
networks:
  getaroundnetwork:
    driver: bridge
